name: Create Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm install npm@latest -g
    - run: |
        cd model      && npm run ci-build && cd ..
        cd visualizer && npm run ci-build && cd ..
        cd ide-common && npm run ci-build && cd ..
        cd ide-app    && npm run ci-build && cd ..
        cd ide-worker && npm run ci-build && cd ..
      env:
        NPM_CONFIG_LOGLEVEL: verbose