name: Enrich Release
on:
  release:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bruceadams/get-release@v1.2.1
      id: get_release
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        npm install npm@latest -g
    - run: |
        cd model      && npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }} && npm run ci-release && cd ..
        cd visualizer && npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }} && npm run ci-release && cd ..
        cd ide-common && npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }} && npm run ci-release && cd ..
        cd ide-app    && npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }} && npm run ci-release && cd ..
        cd ide-worker && npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }} && npm run ci-release && cd ..
      env:
        NPM_CONFIG_LOGLEVEL: verbose
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./model/dist/browser/browser.js
        asset_name: cube-codes-model-${{ steps.get_release.outputs.tag_name }}-browser.js
        asset_content_type: application/javascript
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./visualizer/dist/browser/browser.js
        asset_name: cube-codes-visualizer-${{ steps.get_release.outputs.tag_name }}-browser.js
        asset_content_type: application/javascript
    - run: |
        cd model/dist/docs      && zip -r ../docs.zip . && cd ../../..
        cd visualizer/dist/docs && zip -r ../docs.zip . && cd ../../..
        cd ide-common/dist/docs && zip -r ../docs.zip . && cd ../../..
        cd ide-app/dist/docs    && zip -r ../docs.zip . && cd ../../..
        cd ide-worker/dist/docs && zip -r ../docs.zip . && cd ../../..
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./model/dist/docs.zip
        asset_name: cube-codes-model-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./visualizer/dist/docs.zip
        asset_name: cube-codes-visualizer-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./ide-common/dist/docs.zip
        asset_name: cube-codes-ide-common-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./ide-app/dist/docs.zip
        asset_name: cube-codes-ide-app-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./ide-worker/dist/docs.zip
        asset_name: cube-codes-ide-worker-${{ steps.get_release.outputs.tag_name }}-docs.zip
        asset_content_type: application/zip
    - run: |
        mkdir -p ide/dist/web/${{ steps.get_release.outputs.tag_name }}
        cp --recursive --parents ide-app/index.html ide-app/favicon.ico ide-app/images ide-app/styles ide-app/dist/browser/browser.js ide/dist/web/${{ steps.get_release.outputs.tag_name }}
        cp --recursive --parents ide-worker/worker.js ide-worker/dist/browser/browser.js ide-worker/dist/editor-docs ide/dist/web/${{ steps.get_release.outputs.tag_name }}
        cp ide-app/index.html ide/dist/web
        sed -i -- 's/~~~versionDirectory\/../${{ steps.get_release.outputs.tag_name }}\/ide-app/g' ide/dist/web/index.html
        sed -i -- 's/~~~version/${{ steps.get_release.outputs.tag_name }}/g' ide/dist/web/index.html
        cd ide/dist/web && zip -r ../web.zip . && cd ../../..
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./ide/dist/web.zip
        asset_name: cube-codes-ide-${{ steps.get_release.outputs.tag_name }}-web.zip
        asset_content_type: application/zip